---
# cloud-config
hostname: ${hostname}
manage_etc_hosts: true

# System updates
package_update: true
package_upgrade: true

# Install basic packages
packages:
  - curl
  - wget
  - htop
  - vim
  - git
  - ufw
  - fail2ban
  - unattended-upgrades
  - python3
  - python3-pip

# Configure automatic updates
write_files:
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Automatic-Reboot "false";
      Unattended-Upgrade::Automatic-Reboot-Time "02:00";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";

# Basic firewall setup
runcmd:
  - systemctl enable unattended-upgrades
  - systemctl start unattended-upgrades
  - ufw --force enable
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow ssh
  - systemctl enable fail2ban
  - systemctl start fail2ban

# Set timezone
timezone: UTC

# Configure SSH
ssh_pwauth: false
disable_root: true

# Final reboot to ensure all changes take effect
power_state:
  mode: reboot
  delay: "+1"
  message: "Rebooting after initial setup"
