# Configuration for GitHub labeler
# https://github.com/actions/labeler

# Infrastructure as Code
infrastructure:
  - changed-files:
      - any-glob-to-any-file: "terraform/**/*"
      - any-glob-to-any-file: "ansible/**/*"
      - any-glob-to-any-file: "configs/domains.yml"
      - any-glob-to-any-file: "configs/environments.yml"
      - any-glob-to-any-file: "ansible.cfg"
      - any-glob-to-any-file: "Vagrantfile"
      - any-glob-to-any-file: "vagrant.yml"

# Automation & CI/CD
automation:
  - changed-files:
      - any-glob-to-any-file: "scripts/**/*"
      - any-glob-to-any-file: ".github/**/*"
      - any-glob-to-any-file: ".pre-commit-config.yaml"
      - any-glob-to-any-file: "pyproject.toml"
      - any-glob-to-any-file: "uv.lock"

# Documentation
docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**/*"
      - any-glob-to-any-file: "README.md"
      - any-glob-to-any-file: "mkdocs.yml"
      - any-glob-to-any-file: "scripts/README.md"
      - any-glob-to-any-file: "terraform/README.md"
      - any-glob-to-any-file: "ansible/roles/*/README.md"

# Configuration files
config:
  - changed-files:
      - any-glob-to-any-file: "configs/**/*"
      - any-glob-to-any-file: ".gitleaks.toml"
      - any-glob-to-any-file: ".gitleaksignore"
      - any-glob-to-any-file: ".trivyignore"
      - any-glob-to-any-file: ".yamllint.yml"
      - any-glob-to-any-file: ".tflint.hcl"
      - any-glob-to-any-file: ".ansible-lint"
      - any-glob-to-any-file: "renovate.json"
      - any-glob-to-any-file: ".python-version"
      - any-glob-to-any-file: ".vscode/**/*"
      - any-glob-to-any-file: ".cursor/**/*"

# Monitoring & Observability
monitoring:
  - changed-files:
      - any-glob-to-any-file: "monitoring/**/*"
      - any-glob-to-any-file: "ansible/playbooks/monitoring/**/*"
      - any-glob-to-any-file: "ansible/tasks/monitoring-integration.yml"
      - any-glob-to-any-file: "ansible/tasks/service-monitoring.yml"

# Security
security:
  - changed-files:
      - any-glob-to-any-file: "ansible/playbooks/security/**/*"
      - any-glob-to-any-file: "ansible/tasks/firewall.yml"
      - any-glob-to-any-file: "terraform/modules/security/**/*"
      - any-glob-to-any-file: ".gitleaks.toml"
      - any-glob-to-any-file: ".gitleaksignore"
      - any-glob-to-any-file: ".trivyignore"

# Database & Storage
database:
  - changed-files:
      - any-glob-to-any-file: "ansible/playbooks/infrastructure/database-cluster.yml"
      - any-glob-to-any-file: "ansible/playbooks/infrastructure/backup-setup.yml"
      - any-glob-to-any-file: "ansible/playbooks/validation/backup-verification.yml"

# Emergency & Operations
ops:
  - changed-files:
      - any-glob-to-any-file: "ansible/playbooks/emergency/**/*"
      - any-glob-to-any-file: "ansible/playbooks/operations/**/*"
      - any-glob-to-any-file: "ansible/playbooks/maintenance/**/*"
      - any-glob-to-any-file: "ansible/playbooks/users/**/*"

# Service-specific labels (only for the main ATL services)
atl-services:
  - changed-files:
      - any-glob-to-any-file: "ansible/playbooks/domains/templates/atl_services*"

atl-tools:
  - changed-files:
      - any-glob-to-any-file: "ansible/playbooks/domains/templates/atl_tools*"

atl-dev:
  - changed-files:
      - any-glob-to-any-file: "ansible/playbooks/domains/templates/atl_dev*"

atl-chat:
  - changed-files:
      - any-glob-to-any-file: "ansible/playbooks/domains/templates/atl_chat*"

atl-wiki:
  - changed-files:
      - any-glob-to-any-file: "ansible/playbooks/domains/templates/atl_wiki*"

# Tux bot
tux:
  - changed-files:
      - any-glob-to-any-file: "ansible/roles/tux/**/*"
