---
# YAML Linting Configuration for All Things Linux Infrastructure
# Complements ansible-lint with YAML-specific formatting rules

extends: default

rules:
  # Line length - allow longer lines for readability
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - use 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments - require space after #
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Comments indentation - disabled for ansible-lint compatibility
  comments-indentation: false

  # Document directives - allow multiple documents
  document-start:
    present: true
  document-end:
    present: false

  # Octal values - enabled for ansible-lint compatibility
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  # Empty lines
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1

  # Key ordering - don't enforce alphabetical order
  key-ordering: disable

  # Truthy values - allow yes/no/on/off for Ansible compatibility
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false

  # Brackets and braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Quoted strings - allow both single and double quotes
  quoted-strings:
    quote-type: any
    required: false
