---
depends:
  - role: docker
    when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
galaxy_info:
  author: All Things Linux
  description: Deploys the Tux Discord bot as a Docker Compose service
  company: All Things Linux
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
