---
galaxy_info:
  role_name: system
  author: ATL Infrastructure Team
  description: Base system configuration and /etc management
  company: All Things Linux
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - system
    - configuration
    - security
    - infrastructure
    - etc

dependencies: []
