---
# Staff Management Configuration for All Things Linux
# This file defines all staff roles, permissions, and access levels

# Staff Role Definitions
staff_roles:
  # Management Roles
  administrator:
    description: "Overall management of the community"
    permissions:
      - full_server_access
      - user_management
      - service_management
      - financial_access
      - policy_creation
    sudo_access: true
    ssh_access: ["all"]
    services_access: ["all"]
  assistant_administrator:
    description: "Support for administrators"
    permissions:
      - limited_server_access
      - user_management
      - service_monitoring
      - task_management
    sudo_access: true
    ssh_access: ["core_infrastructure", "application_services"]
    services_access: ["monitoring", "wiki", "tools"]
  # Finance Role
  treasurer:
    description: "Financial oversight and management"
    permissions:
      - financial_access
      - budget_management
      - expense_tracking
      - donation_management
    sudo_access: false
    ssh_access: ["monitoring"]
    services_access: ["monitoring", "backup"]
  # Systems Roles
  systems_administrator:
    description: "Server and infrastructure management"
    permissions:
      - full_server_access
      - service_management
      - security_management
      - backup_management
    sudo_access: true
    ssh_access: ["all"]
    services_access: ["all"]
  fullstack_developer:
    description: "Full-stack web development"
    permissions:
      - deploy_access
      - database_access
      - service_restart
      - log_access
    sudo_access: false
    ssh_access: ["web_servers", "database_servers", "application_services"]
    services_access: ["web", "database", "wiki", "tools", "dev"]
  frontend_developer:
    description: "Frontend web development"
    permissions:
      - web_deploy_access
      - static_content_management
      - cdn_management
    sudo_access: false
    ssh_access: ["web_servers"]
    services_access: ["web", "wiki", "tools"]
  backend_developer:
    description: "Backend development and APIs"
    permissions:
      - api_deploy_access
      - database_access
      - service_restart
      - log_access
    sudo_access: false
    ssh_access: ["database_servers", "application_services"]
    services_access: ["database", "api", "tools", "dev"]
  python_developer:
    description: "Python development, especially Discord bot"
    permissions:
      - bot_deploy_access
      - service_restart
      - log_access
      - python_env_management
    sudo_access: false
    ssh_access: ["tools"]
    services_access: ["tools", "dev", "monitoring"]
  # Moderation Roles
  director_of_moderation:
    description: "Oversee moderation team and policies"
    permissions:
      - moderation_tools_access
      - user_management
      - policy_enforcement
      - team_management
    sudo_access: false
    ssh_access: ["tools", "monitoring"]
    services_access: ["monitoring", "tools"]
  senior_moderator:
    description: "Senior moderation responsibilities"
    permissions:
      - advanced_moderation_tools
      - user_management
      - policy_enforcement
    sudo_access: false
    ssh_access: ["tools"]
    services_access: ["monitoring", "tools"]
  moderator:
    description: "Community moderation"
    permissions:
      - basic_moderation_tools
      - user_warnings
      - content_management
    sudo_access: false
    ssh_access: []
    services_access: ["tools"]
  # Creative Roles
  creative_director:
    description: "Creative vision and brand management"
    permissions:
      - asset_management
      - brand_guidelines
      - content_approval
    sudo_access: false
    ssh_access: ["web_servers"]
    services_access: ["web", "wiki", "tools"]
  graphic_designer:
    description: "Visual content creation"
    permissions:
      - asset_upload
      - web_content_management
    sudo_access: false
    ssh_access: ["web_servers"]
    services_access: ["web", "wiki"]
  pixel_artist:
    description: "Pixel art creation"
    permissions:
      - asset_upload
      - game_content_management
    sudo_access: false
    ssh_access: []
    services_access: ["web", "tools"]
# Staff Members Configuration
# Note: Individual staff members should be defined in separate encrypted files
# for security purposes. This is just the structure.
staff_structure:
  management:
    administrators: []
    assistant_administrators: []
    treasurers: []
  systems:
    systems_administrators: []
    fullstack_developers: []
    frontend_developers: []
    backend_developers: []
    python_developers: []
  moderation:
    directors_of_moderation: []
    senior_moderators: []
    moderators: []
  creative:
    creative_directors: []
    graphic_designers: []
    pixel_artists: []
# Service-specific access control
service_access_matrix:
  # Core Infrastructure
  web_servers:
    full_access: ["administrator", "systems_administrator"]
    deploy_access: ["fullstack_developer", "frontend_developer"]
    read_access: ["creative_director", "graphic_designer"]
  database_servers:
    full_access: ["administrator", "systems_administrator"]
    rw_access: ["fullstack_developer", "backend_developer"]
    read_access: ["python_developer"]
  # Application Services
  discord_services:
    full_access: []
    deploy_access: []
    moderate_access: []
    read_access: []
  wiki_services:
    full_access: ["administrator", "systems_administrator"]
    deploy_access: ["fullstack_developer", "frontend_developer"]
    content_access: ["creative_director", "graphic_designer"]
  tools_services:
    full_access: ["administrator", "systems_administrator"]
    deploy_access: ["fullstack_developer", "backend_developer"]
    app_access: ["creative_director"]
  # Monitoring
  monitoring_servers:
    full_access: ["administrator", "systems_administrator"]
    read_access: ["assistant_administrator", "treasurer", "director_of_moderation"]
# SSH Key Management
ssh_key_management:
  key_rotation_days: 90
  key_strength: 4096
  allowed_key_types: ["rsa", "ed25519"]
  key_backup_enabled: true

# Audit and Compliance
audit_settings:
  login_logging: true
  command_logging: true
  file_access_logging: true
  audit_retention_days: 365
  compliance_checks: true
