---
# Ansible Collections Requirements for All Things Linux Infrastructure
# Install with: ansible-galaxy collection install -r collections/requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.5.0"

  - name: community.general
    version: ">=7.0.0"

  - name: community.docker
    version: ">=3.0.0"

  - name: hetzner.hcloud
    version: ">=4.0.0"
