---
galaxy_info:
  role_name: docker
  author: ATL Infrastructure Team
  description: Install and configure Docker
  company: All Things Linux
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - focal
        - bionic
    - name: Debian
      versions:
  galaxy_tags:
    - docker
    - containers
    - infrastructure

dependencies: []
