---
environments:
  production:
    name: "Production"
    domain_suffix: ""
    monitoring: true
    backup_retention: 30

  staging:
    name: "Staging"
    domain_suffix: "staging."
    monitoring: true
    backup_retention: 7

  development:
    name: "Development"
    domain_suffix: "dev."
    monitoring: false
    backup_retention: 3
