---
# Ansible Secrets Configuration
# Copy this file to secrets.yml and fill in actual values
# Add secrets.yml to .gitignore (already done)

# NOTE: For Terraform secrets, prefer environment variables:
# export TF_VAR_hetzner_token="your_token"
# export TF_VAR_cloudflare_api_token="your_token"

# Cloudflare credentials (for Ansible DNS management)
cloudflare:
  api_token: "your_cloudflare_api_token_here"
  zone_id: "your_zone_id_here"

# Database passwords (for Ansible database setup)
database:
  root_password: "generate_strong_password"
  app_password: "generate_strong_password"

# Application secrets (for Ansible service configuration)
app_secrets:
  secret_key: "generate_random_secret_key"
  jwt_secret: "generate_jwt_secret"

# Monitoring credentials (for Ansible monitoring setup)
monitoring:
  grafana_admin_password: "generate_strong_password"
  prometheus_basic_auth: "generate_basic_auth"

# Backup encryption (for Ansible backup configuration)
backup:
  encryption_key: "generate_encryption_key"

# SMTP configuration (for Ansible notification setup)
smtp:
  username: "notifications@allthingslinux.org"
  password: "generate_smtp_password"
  host: "smtp.example.com"

# SSL certificates (for Ansible SSL management)
ssl:
  acme_email: "admin@allthingslinux.org"
# USAGE NOTES:
# - This file is for Ansible playbook secrets
# - Terraform secrets should use environment variables
# - Never commit this file to git
# - Use ansible-vault for additional encryption if needed
