---
# Hostname and /etc/hosts configuration

- name: subtasks | hostname | Set system hostname
  ansible.builtin.hostname:
    name: "{{ system_hostname }}"
  notify: Restart systemd-resolved

- name: subtasks | hostname | Generate /etc/hosts file from template
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart systemd-resolved
