---
# Locale configuration

- name: subtasks | locale | Install locales package
  ansible.builtin.package:
    name: locales
    state: present
  when: ansible_os_family == "Debian"

- name: subtasks | locale | Set locale_list fact
  ansible.builtin.set_fact:
    locale_list: "{{ ([system_locale] + (system_language | default('')).split(':')) | unique | list }}"
  when: system_language is defined and system_language

- name: subtasks | locale | Generate required locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ ([system_locale] + (system_language | default('')).split(':')) | unique | list }}"
  when: ansible_os_family == "Debian"

- name: subtasks | locale | Get current locale and language configuration
  ansible.builtin.command: localectl status
  register: locale_status
  changed_when: false

- name: subtasks | locale | Configure locale using localectl
  ansible.builtin.command: >
    localectl set-locale
    LANG={{ system_locale }}
    {% if system_language is defined %}LANGUAGE={{ system_language }}{% endif %}
  become: true
  when:
    - "'LANG=#{system_locale}' not in locale_status.stdout"
    - system_language is not defined or "'LANGUAGE=#{system_language}' not in locale_status.stdout"

- name: subtasks | locale | Verify locale is set correctly
  ansible.builtin.command: localectl status
  register: current_locale
  changed_when: false

- name: subtasks | locale | Display current locale
  ansible.builtin.debug:
    msg: "{{ current_locale.stdout_lines }}"
