---
# Environment Configuration - Single Source of Truth
# This file defines all environment-specific configurations

environments:
  production:
    name: "Production"
    domain_suffix: ""
    monitoring: true
    backup_retention: 30
    network_range: "10.0.0.0/16"
    location: "ash"
    backups_enabled: true
    security:
      allowed_ips: ["0.0.0.0/0"] # Configure appropriately
      web_ports: [80, 443]
      strict_access: true
    features:
      ssl_enabled: true
      monitoring_enabled: true
      backup_enabled: true

  staging:
    name: "Staging"
    domain_suffix: "staging."
    monitoring: true
    backup_retention: 7
    network_range: "10.2.0.0/16"
    location: "ash"
    backups_enabled: true
    security:
      allowed_ips: ["0.0.0.0/0"] # Configure appropriately
      web_ports: [80, 443, 8080]
      strict_access: false
    features:
      ssl_enabled: true
      monitoring_enabled: true
      backup_enabled: true

  development:
    name: "Development"
    domain_suffix: "dev."
    monitoring: false
    backup_retention: 3
    network_range: "10.1.0.0/16"
    location: "nbg1"
    backups_enabled: false
    security:
      allowed_ips: ["0.0.0.0/0"]
      web_ports: [80, 443, 8080, 3000]
      strict_access: false
    features:
      ssl_enabled: true
      monitoring_enabled: false
      backup_enabled: false
