---
# Handlers for system role

- name: Restart ssh
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: Restart ntp
  ansible.builtin.service:
    name: "systemd-timesyncd"
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Test logrotate
  ansible.builtin.command: logrotate -d /etc/logrotate.conf
  changed_when: false
  failed_when: false

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
