---
# Handlers for system role

- name: Restart ssh
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: Restart networking
  ansible.builtin.service:
    name: networking
    state: restarted
  when: ansible_os_family == "Debian"

- name: Restart ntp
  ansible.builtin.service:
    name: "{{ 'ntp' if ansible_os_family == 'Debian' else 'ntpd' }}"
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Test logrotate
  ansible.builtin.command: logrotate -d /etc/logrotate.conf
  changed_when: false
  failed_when: false
